services:
  - type: web
    name: tewfiksoft-hr-bot
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: BOT_TOKEN
        value: 8675308284:AAF1LCwdFKZZdD6lQXcyJJImXwRz8ColvBM
      - key: ADMIN_CHAT_ID
        value: 8626592284
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
